name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest ]
        # linux and macOS are currently busted
        #os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683       # v4.2.2
      with:
        submodules: true

    - name: Install Prerequisites Linux
      if: ${{matrix.os == 'ubuntu-latest'}}
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh
        echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
        sudo dpkg-reconfigure man-db
        sudo apt install --no-install-recommends -y liburing-dev pkg-config

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2.0.2
      with:
        cmake-version: '3.31'

    - name: Run Workflow
      run: |
        cmake --version
        cmake --workflow --preset default
